export const PATH_NAME = {
  ROOT: '/',
  ERROR_404: '/404',
  PLAY_BACKGROUND: '/playbackground',
  LOGIN: '/login',
  SONG: '/song',
  SONG_ADD: '/song/add',
  SONG_LISTS: '/song/lists',
  ARTISTS: '/artist',
  TOOLS: '/tools',
  TOOLS_NOTEBOT: '/tools/note-bot',
  AMPLITUDE: 'https://analytics.amplitude.com/login/amanotesmusic',
  APP: '/app',
  APP_ADD: '/app/add',
  APP_LISTS: '/app/lists',
  USERS: '/users',
  LICENSES: '/licenses',
  LICENSES_ADD: '/licenses/add',
  LICENSES_LISTS: '/licenses/lists',
  LOCATION: '/location',
  SYSTEM: '/system',
  SYSTEM_MASS_TAGGING: '/system/mass-tagging',
  SYSTEM_MASS_EDITING: '/systems/mass-editing',
};
